version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: app
    environment:
      TODO_ENV: ${TODO_ENV}
      PORT: ${PORT}
      DSN: ${DSN}
      EXTERNAL_API: ${EXTERNAL_API}
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    restart: always

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: new_password
      MYSQL_DATABASE: finatext_db
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
